=== g4brielosoares/BCC/Engenharia de software/xsd/alunos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="alunos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="aluno" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string"/>
                            <xs:element name="matricula" type="xs:string"/>
                            <xs:element name="curso" type="xs:string"/>
                            <xs:element name="idade">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="18"/>
                                        <xs:maxInclusive value="30"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== g4brielosoares/BCC/Engenharia de software/xsd/alunos.xml
<?xml version="1.0" encoding="UTF-8"?>
<alunos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="alunos.xsd">
    <aluno>
        <nome>João da Silva</nome>
        <matricula>20231001</matricula>
        <curso>Ciência da Computação</curso>
        <idade>20</idade>
    </aluno>
    <aluno>
        <nome>Maria Souza</nome>
        <matricula>20231002</matricula>
        <curso>Engenharia de Software</curso>
        <idade>22</idade>
    </aluno>
    <aluno>
        <nome>Gabriel Soares</nome>
        <matricula>20231003</matricula>
        <curso>Ciência da Computação</curso>
        <idade>20</idade>
    </aluno>
</alunos>
